version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g yarn typescript
      - cd server && yarn install
  build:
    commands:
      - cd server && yarn build

artifacts:
  files:
    - 'server/yarn.lock'
    - 'server/package.json'
    - 'server/build/**/*'
    - 'server/.platform/**/*' # AWS Elastic Beanstalk configuration files
    - 'server/.ebextensions/**/*' # AWS Elastic Beanstalk configuration files
  discard-paths: no
